# ==================== SONARCLOUD CONFIG ====================
sonar.projectKey=foudja-laeti_helpdesk
sonar.organization=foudja-laeti
sonar.projectName=Helpdesk Django App
sonar.projectVersion=1.0

# Sources
sonar.sources=helpdeskapp
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/tests.py

# Tests
sonar.tests=helpdeskapp
sonar.test.inclusions=**/tests.py

# Couverture de code (généré par coverage.py)
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.13

# Encodage
sonar.sourceEncoding=UTF-8