# Generated by Django 5.1.4 on 2026-01-24 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdeskapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='adresse',
            field=models.CharField(
                blank=True,
                help_text='Adresse complète (ville, quartier)',
                max_length=300,
                null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='technicien',
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    'role': 'technicien'},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='technicien_demandes',
                to='helpdeskapp.utilisateur'),
        ),
    ]
